[Platforms] Restore previous configuration flags for base armv7l architecture
Using only `-mcpu=generic-armv7-a` causes an error in the assembler with GCC 5:

```console
% julia --compile=min -e 'using BinaryBuilderBase; BinaryBuilderBase.runshell(Platform("armv7l", "linux"); preferred_gcc_version=v"5")'
sandbox:${WORKSPACE} # echo 'int main(){}' | /opt/arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc -x c - -mcpu=generic-armv7-a
Assembler messages:
Error: unknown cpu `generic-armv7-a'
Error: unrecognized option -mcpu=generic-armv7-a
```

We may have to revise how GCC is compiled for this platform, but this is for
another day.